server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: C:\CloudConfig
          uri: https://github.com/chj970702/spring-cloud-config.git
          default-label: main # github repo branch name


