server:
  port: 8888

spring:
  application:
    name: config-service
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest

#  profiles:
#    active: native
  cloud:
    config:
      server:
#        native:
#          search-locations: file:///C:/CloudConfig
        git:
#          uri: C:\CloudConfig
          uri: https://github.com/chj970702/spring-cloud-config.git
          default-label: main # github repo branch name
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
